import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Loader2, Sparkles, Cpu } from 'lucide-react';
import { ChatMessage } from '@/domain/repositories/ISessionRepository';

interface ChatInterfaceProps {
    messages: ChatMessage[];
    onSendMessage: (message: string) => void;
    onInputChange?: (input: string) => void;
    isLoading: boolean;
    activeSkillName?: string;
}

export const ChatInterface: React.FC<ChatInterfaceProps> = ({ messages, onSendMessage, onInputChange, isLoading, activeSkillName }) => {
    const [input, setInput] = useState('');
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!input.trim() || isLoading) return;

        onSendMessage(input);
        setInput('');
    };

    return (
        <div className="flex flex-col h-full bg-gray-900 rounded-lg overflow-hidden relative">
            {/* Messages Area */}
            <div className="flex-1 overflow-y-auto p-4 space-y-6 custom-scrollbar">
                {messages.length === 0 && (
                    <div className="flex flex-col items-center justify-center h-full text-gray-500 pb-20">
                        <div className="w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg shadow-blue-500/20 animate-float">
                            <Sparkles className="w-10 h-10 text-white" />
                        </div>
                        <h3 className="text-xl font-semibold text-white mb-2">무엇을 도와드릴까요?</h3>
                        <p className="text-sm max-w-md text-center">
                            {activeSkillName
                                ? `현재 '${activeSkillName}' 스킬이 활성화되어 있습니다.`
                                : "좌측 상단에서 스킬을 선택하거나 바로 대화를 시작하세요."}
                        </p>
                    </div>
                )}

                {messages.map((msg) => (
                    <div
                        key={msg.id}
                        className={`flex items-start gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
                    >
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 border border-white/10
              ${msg.role === 'user'
                                ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/10'
                                : 'bg-gray-800 text-green-400 shadow-lg'}`}>
                            {msg.role === 'user' ? <User size={16} /> : <Bot size={16} />}
                        </div>

                        <div className={`max-w-[80%] rounded-2xl p-4 text-sm whitespace-pre-wrap shadow-sm
              ${msg.role === 'user'
                                ? 'bg-blue-600 text-white rounded-tr-none'
                                : 'bg-white/5 border border-white/5 text-gray-200 rounded-tl-none'}`}>
                            {msg.content}
                            {msg.skillId && msg.role === 'assistant' && (
                                <div className="mt-2 pt-2 border-t border-white/10 text-[10px] uppercase tracking-wider opacity-50 flex items-center gap-1">
                                    <Cpu size={10} />
                                    Generated by AI
                                </div>
                            )}
                        </div>
                    </div>
                ))}

                {isLoading && (
                    <div className="flex items-start gap-4">
                        <div className="w-8 h-8 rounded-lg bg-gray-800 text-green-400 flex items-center justify-center shrink-0 border border-white/10">
                            <Loader2 className="w-4 h-4 animate-spin" />
                        </div>
                        <div className="bg-white/5 border border-white/5 rounded-2xl rounded-tl-none p-4 text-sm text-gray-400">
                            Thinking...
                        </div>
                    </div>
                )}
                <div ref={messagesEndRef} />
            </div>

            {/* Input Area */}
            <div className="p-4 bg-gray-900 border-t border-white/5">
                <form onSubmit={handleSubmit} className="relative">
                    <input
                        type="text"
                        value={input}
                        onChange={(e) => {
                            setInput(e.target.value);
                            onInputChange?.(e.target.value);
                        }}
                        placeholder="AI에게 무엇이든 물어보세요..."
                        disabled={isLoading}
                        className="w-full pl-5 pr-14 py-4 rounded-xl border border-white/10 bg-white/5 text-gray-100 placeholder:text-gray-600 focus:outline-none focus:ring-1 focus:ring-blue-500/50 focus:bg-white/10 transition-all disabled:opacity-50"
                    />
                    <button
                        type="submit"
                        disabled={isLoading || !input.trim()}
                        className="absolute right-2 top-2 bottom-2 aspect-square bg-blue-600 text-white rounded-lg hover:bg-blue-500 disabled:opacity-0 disabled:scale-75 transition-all flex items-center justify-center shadow-lg shadow-blue-500/20"
                    >
                        <Send size={18} />
                    </button>
                </form>
                <div className="text-center mt-2 text-[10px] text-gray-600">
                    AI can make mistakes. Please review generated results.
                </div>
            </div>
        </div>
    );
};
